### ISSUE TITLE
Fix React project tests

### ISSUE THREAD

**Issue by vanilla-james** [beoble/beoble-toolkit#79]
all tests when running `nx test react` in `beoble/beoble-toolkit/packages/react` fail
![image](https://user-images.githubusercontent.com/6829451/194386955-48f09b77-fac2-4f25-80b0-06c1b5751174.png)

**Comment by bamnenim-kryptonium** [comment]
As I talked to you, there is no actual test codes in `react` library
But we should have some one day.
